### ISSUE TITLE
Finger print extraction (Part 6/8): ATECC608A Development With Cryptoauthlib - Data Types of Slots

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#19]
### Problem 
Data Zone  of 1,208 bytes is split into 16 general-purpose read-only or read/write memory slots. The slots are divided in the following way:
- Slots 0-7 Contain 36 Bytes
- Slot 8 Contains 416 Bytes
- Slots 9-15 Contain 72 Bytes
The access policies of the slots define the kind of cryptographic operations that can be performed on them. Therefore, a clear understanding of the role of every slot, the data type it supports and the supported modification must be known before making any modifications to the device.

### Solution
- [x]  Understanding data types in detail:
The data types that the slot policies hold are:
- Private Keys
- Public Keys
- Certificate Storage
- Secure Boot
- Secret Key
- AES Key Storage
- I/O Protection Key
- General Data Storage

- [x] Understanding access policies of data types
- Referring: https://onlinedocs.microchip.com/pr/GUID-E8090678-FB6F-4FDB-B2FD-C019408533ED-en-US-2/index.html?GUID-5118176F-10E9-41D3-9FDD-E36F38172F9F for guidance

- [x] Key Attestation 
 The attestation key is stored in a specially configured slot that can only be used to sign messages about the internal state and contents of the secure element.
-With the default configuration, key attestations  to be performed as an experiment using cryptoauthlib

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/19?planning-poker) with ZenHub @lucy-sha512 @nilesh-uniris @sauravkr-diat-ai
