### ISSUE TITLE
Fingerprint Image Segmentation (Part 1/3)

### ISSUE THREAD

**Issue by sauravkr-diat-ai** [archethic-foundation/biometrics#20]
### Problem to solve

The previous experiments were based on the images with some unwanted background. These background acts as noise in the image which were adding to spurious minutiae detection.

### Solution

![Screenshot (1142)](https://user-images.githubusercontent.com/71205003/162108763-755d6ec0-6026-44ec-92bd-4fed0581de66.png)

Image segmentation is the process to identify the region of interest in the given image. The proposed solution is to use image segmentation technique to precisely locate fingerprint region in an image so that further processing is applied to that specific area. 

**Steps**
- [x] Study & **experiment on the classical approach** of image segmentation. [code+document]
It generally involve technique viz. clustering , edge detection & graphical theoretic(spectral clustering) for image segmentation. 

.
- [x]  Study the **deep learning based method** for image segmentation. [Document]
There are few deep learning architecture for the image segmentation purpose viz. u-Net, FCN, R-CNN, SegNet. This task aim to understand their working principle and flow of implementation. Moreover, to reach to conclusion the most suitable architecture for fingerprint image.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/20?planning-poker) with ZenHub @internet-zero @lucy-sha512 @nilesh-uniris @sauravkr-diat-ai

**Comment by AmodD** [comment]
can we split the issue into different issues by grouping 
- study tasks
- prep data
- train and test
