### ISSUE TITLE
Vectorized Fingerprint Image 

### ISSUE THREAD

**Issue by sauravkr-diat-ai** [archethic-foundation/biometrics#21]
### Problem to solve

The subsequent stage in AE BIOMETRIC project pipeline is to generate vectorized image based on minutiae extraction. This vectorized image data is to be used further for key generation.

### Solution

Extraction of minutiae has been done in #10 where it is possible to identify these minutiae point. The proposed solution is to extend work on those identified point to get vectorized image as its output.  
![Screenshot (1143).png](https://images.zenhubusercontent.com/6218a9212c11a2e8532beeac/52d18a00-ecf5-4215-accf-60dc4e8a4e02)

**Steps**

- [x] **Prepare the code flow chart** to show the flow of input to desired output.[document]
.
- [x] **Extract the minutiae location**. [code]
Minutiae location extraction is an intermediate step. We target to extract minutiae location of two specific kind of minutiae i.e. ridge termination & ridge bifurcation in the fingerprint image.
. 
- [x] **Generate the vector image.** [code] 
Build a numpy array with 0 values. Append the array values at the coordinate where minutiae has been detected differentiating the types of minutiae in previous task.

- [ ] **export the matrix to CSV** [code]

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/21?planning-poker) with ZenHub @internet-zero @lucy-sha512 @nilesh-uniris @sauravkr-diat-ai
