### ISSUE TITLE
Finger print extraction (Part 7/8): ATECC608A Development With Cryptoauthlib- Create asymmetric keys with random data

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#23]
### Problem
AEBiometric requires to generate asymmetric keys - **Public key** and **Private key**  from biometric data. These keys use some random source to to be generated. In this experiment we will explore how to use ATECC608a to create such keys using random data. We first generate these random data using cryptoauth library  and store it in a slot .

### Solution

- [x] Explore how to create asymmetric keys with random data. 
 This task will answer the following queries:

- How to create ECC keys with random data?
- Is the above possible in ATECC608a?
- If yes , then how it is done?
- If no, is there any alternative?
- [x] Create random data and keep it in a slot

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/23?planning-poker) with ZenHub @lucy-sha512 @nilesh-uniris @sauravkr-diat-ai
