### ISSUE TITLE
Finger print extraction (Part 8/8): ATECC608A Development With Cryptoauthlib - Key Generation With Raw Data and Biometrics

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#24]
### Problem
A thorough exploration of Cryptoauthlib and ATECC608A cryptoprocessor has helped to identify their capabilities.  It is concluded that there is no direct way of creating asymmetric keys with Cryptoauthlib API on ATECC608A. However,  existing functions could be utilized to generate ECC keys .
The functions that could be utilized are :

-  calib_genkey()
- calib_genkey_base()
- calib_get_pubkey()
- calib_nonce()
-  calib_nonce_gen_session_key()
- calib_priv_write()
- calib_info_privkey_valid()
- calib_kdf()

### Solution
There could be two ways in which these functions can be utilized to generate assymetric keys:
#### Solution 1

- [x] Generate ECC keys with calib_nonce()

```
generate_ECC_key_nonce(data)
{
1. Generate 32 bit ECC key with random data
nonce=calib _nonce(data)
private _key=nonce
3. Check whether it is a valid ECC key
valid = calib_info_privkey_valid(private_key)
4. Generate public key if the ECC key generated is valid
 if(valid)

   pubkey= calib_get_pubkey()
}
5. Return the (public , private) key pair
    Return (pubkey, private_key)
}
```

 

- [x] Solution 2 : Eliminate Device Dependency

- Alternative usage of cryptoauth API and ATECC608a  for key generation with raw data
- Remove the dependency on hardware 
- Use externally generated key and write in ATECC608a slot 2
- Use derive() key function with input (external key in slot 2, input data/nonce) to generate final private key
- Use  pubkey= calib_get_pubkey() to get the public key from the derived key

- [x] Testing With Sign and Verification

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/24?planning-poker) with ZenHub @lucy-sha512 @nilesh-uniris @sauravkr-diat-ai

**Comment by lucy-sha512** [comment]
Modified Algorithm for Key Generation

```
generate_ECC_key_nonce(data)
{
1. Generate private key in slot
calib_gen_key(slot, pubkey)


2. Generate public key if the ECC key generated is valid
 if(valid)
{
   pubkey= calib_get_pubkey()
}
5. Return the (public , private) key pair
    Return (pubkey, private_key)
}
```

**Comment by lucy-sha512** [comment]
https://github.com/MicrochipTech/cryptoauthlib/issues/294
